# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Rekettye(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, alma: str=None):  # noqa: E501
        """Rekettye - a model defined in Swagger

        :param alma: The alma of this Rekettye.  # noqa: E501
        :type alma: str
        """
        self.swagger_types = {
            'alma': str
        }

        self.attribute_map = {
            'alma': 'alma'
        }
        self._alma = alma

    @classmethod
    def from_dict(cls, dikt) -> 'Rekettye':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The rekettye of this Rekettye.  # noqa: E501
        :rtype: Rekettye
        """
        return util.deserialize_model(dikt, cls)

    @property
    def alma(self) -> str:
        """Gets the alma of this Rekettye.


        :return: The alma of this Rekettye.
        :rtype: str
        """
        return self._alma

    @alma.setter
    def alma(self, alma: str):
        """Sets the alma of this Rekettye.


        :param alma: The alma of this Rekettye.
        :type alma: str
        """
        if alma is None:
            raise ValueError("Invalid value for `alma`, must not be `None`")  # noqa: E501

        self._alma = alma
